---
# tasks file for haproxy

- name: Create HAProxy error templates directory
  file:
    path: /etc/haproxy/errors
    state: directory
    mode: '0755'

- name: Copy haproxy.cfg and reload HAProxy
  template:
    src: "haproxy.{{ name }}.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    owner: haproxy
    group: haproxy
    # setype: named_conf_t
    mode: '0644'
  notify: Restart HAProxy

- name: Copy error pages
  copy:
    src: "errors/"
    dest: "/etc/haproxy/errors/"
    owner: "haproxy"
    group: "haproxy"
    mode: '0644'
  notify: Restart HAProxy

- name: Ensure HAProxy is enabled and running
  service:
    name: haproxy
    state: started
    enabled: yes
